yuku/textcomplete

CHANGELOG.md
src/strategy.js
test/strategy-spec.js

Add cache strategy parameter

---

CHANGELOG.md
src/dropdown.js
src/textcomplete.js
test/integration/dropdown-option-spec.js
test/unit/dropdown-spec.js

Add className dropdown option

---

CHANGELOG.md
src/dropdown.js
test/integration/dropdown-option-spec.js
test/unit/dropdown-spec.js

Add style dropdown option

---

CHANGELOG.md
src/dropdown-item.js
src/textcomplete.js
test/integration/option-spec.js

Add maxCount option

---

CHANGELOG.md
src/dropdown.js
src/utils.js
test/test-helper.js
test/unit/dropdown-spec.js

Add header and footer dropdown options

---

CHANGELOG.md
src/dropdown.js
src/textcomplete.js
test/integration/events-spec.js
test/unit/dropdown-spec.js

Add show, shown, rendered, hide and hidden events to Textcomplete

---

CHANGELOG.md
package.json
src/strategy.js
src/textcomplete.js
test/unit/strategy-spec.js

Context strategy parameter

---

CHANGELOG.md
package.json
src/dropdown.js
src/editor.js
src/textarea.js
test/unit/textarea-spec.js

Support "rtl" direction

---

.jsdoc.json
CHANGELOG.md
CONTRIBUTING.md
README.md
doc/development.md
doc/getting-started.md
doc/tutorials.json
src/dropdown.js
src/strategy.js
src/textcomplete.js

Add getting-started

---

CHANGELOG.md
doc/events.md
src/dropdown.js
src/utils.js
test/unit/dropdown-spec.js
test/unit/utils-spec.js

Custom events

---

CHANGELOG.md
src/completer.js
src/dropdown.js
src/editor.js
src/strategy.js
src/textarea.js
src/textcomplete.js
test/unit/strategy-spec.js
test/unit/textcomplete-spec.js

Enable to finalize Textcomplete

---

CHANGELOG.md
src/textarea.js
src/utils.js

Fix dropdown position when window is scrolled

---

CHANGELOG.md
src/editor.js
src/textarea.js
src/textcomplete.js
test/unit/textarea-spec.js

Divide Editor#move event into Editor#move and Editor#enter events

---

src/completer.js
src/dropdown.js
src/textcomplete.js
test/integration/basic_spec.js
test/integration/dropdown_option_spec.js
test/integration/events_spec.js
test/unit/completer_spec.js
test/unit/dropdown_spec.js
test/unit/textarea_spec.js

Refactor arrow function style

---

CHANGELOG.md
src/doc/index.jade
src/dropdown.js
src/strategy.js
test/integration/strategy_parameters_spec.js

Add id strategy parameter

---

CHANGELOG.md
package.json
src/textarea.js

Use line-height package to fix a minor dropdown position problem

---

CHANGELOG.md
src/dropdown.js
src/dropdown_item.js
test/integration/basic_spec.js
test/test_helper.js
test/unit/dropdown_item_spec.js

Activate hovered dropdown item

---

CHANGELOG.md
src/editor.js
src/textarea.js
test/unit/textarea_spec.js

Don't trigger textcomplete by pressing shift, ctrl, alt and command keys

---

CHANGELOG.md
src/dropdown.js
src/dropdown_item.js
test/integration/dropdown_option_spec.js

Add rotate dropdown option

---

src/editor.js
src/textarea.js
src/textcomplete.js
test/integration/events_spec.js

Deactivate dropdown on esc key

---

CHANGELOG.md
src/doc/index.jade
src/dropdown.js
src/textarea.js
test/unit/dropdown_spec.js
test/unit/textarea_spec.js

Support placement dropdown option

---

package.json
src/completer.js
src/dropdown.js
src/dropdown_item.js
src/textarea.js
src/textcomplete.js
src/utils.js
test/unit/dropdown_item_spec.js
yarn.lock

1. uniqueid: removed together with ID assignments, as they were unused.
2. assignin: regular assignments / `Object.keys(...).forEach`.
2. bindAll: `forEach`.
Refs #73

Remove non-dev lodash dependencies

---

src/dropdown.js
src/utils.js

1. It was only used once.
2. A fragment is unnecessary where it was used.

Remove utils.createFragment

---

README.md
src/textarea.js
src/utils.js
test/unit/textarea_spec.js

Drop IE9 support

---

src/utils.js

Fix CustomEvent on browsers that do not support it

---

src/dropdown.js
src/editor.js
src/search_result.js
src/textcomplete.js
test/unit/textarea_spec.js

* dropdown.js:
Use slice/map in dropdown JS in the for loop.
May be a tiny bit slower, but is more readable and compact.
* editor.js:
Use a string enum for KeyCode, and use strings for values.
Safety is enforced by Flow.
* search_result.js:
Replace != null with !== null
* textcomplete.js:
Inline the buildHandler method
dist/textcomplete.min.js.gz:
before: 8693 bytes
after:  8588 bytes

Minor refactorings

---

src/completer.js
src/dropdown.js
src/dropdown_item.js
src/editor.js
src/strategy.js
src/textarea.js
src/textcomplete.js
test/unit/strategy_spec.js
test/unit/textcomplete_spec.js

"finalize" usually means a method that is called by the garbage collector but this method isn't.

Rename finalize to destroy

---

src/utils.js

Fix incorrect line-height calculation

---

src/dropdown.js

When header/footer are not set

Fix "undefined" appearing in the list

---

doc/events.md
src/textarea.js
test/unit/textarea_spec.js

Dispatch an 'input' event on the textarea element

---

doc/getting-started.md
src/query.js
src/search_result.js
src/strategy.js
test/unit/strategy_spec.js

Accept a function that returns match data

---

.travis.yml
CHANGELOG.md
src/textarea.js
test/unit/textarea_spec.js
test/unit/textcomplete_spec.js

Now autocompletion done by textcomplete is revokable by ctrl-z

Enable to revoke autocompletion by ctrl-z

---

package.json
src/textarea.js
yarn.lock

Update undate to 0.2.0

---

.travis.yml
package.json
yarn.lock

Make sure that dist/textcomplete.min.js is smaller than 7000B
- https://github.com/siddharthkp/bundlesize

Use bundlesize

---

README.md

https://github.com/ngryman/badge-size

Readme: Add gzip size badge

---

src/search_result.js
test/unit/search_result_spec.js

Fix to make SearchResult.replace work with numeric matches

---

src/completer.js
src/dropdown_item.js
src/query.js
src/strategy.js
test/unit/query_spec.js
test/unit/strategy_spec.js

Closes https://github.com/yuku-t/textcomplete/issues/138
Stop importing query.js and dropdown.js form strategy.js and dropdown_item.js respectively to fix circular dependency.

Fix circular dependency

---

src/dropdown.js

Fix dropdown going off screen

---

src/utils.js

Closes: https://github.com/yuku/textcomplete/issues/167

Check typeof window for SSR
